spring.application.name=events

# Nivel do DEBUG do Slf4j
loggin.level.com=DEBUG

#Opcional porque o tomcat já coloca na porta 8080, mas esse comando serve para trocar a porta quando você precisa trocar
server.port=8080

# Driver
spring.datasource.driverClassName=org.h2.Driver

# URL de acesso ao database H2
spring.datasource.url=jdbc:h2:mem:db_events

# Login/senha de acesso ao database H2
spring.datasource.username=admin
spring.datasource.password=admin

# H2 Console (para acessar o banco via navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mapeamento JPA
spring.jpa.hibernate.ddl-auto=update